sudo: false

language: node_js
node_js:
  - 5

# contributors task: need all commits to build the contributors cache correctly
git:
  depth: 100000

env:
  global:
    # GH_TOKEN
    - secure: d1VZ29IbfOn0Re774eOWFpCcSLMd3N49ehmMOF8NiAQBV30NddTr5GVua19sMfCBVryHVu5MaaD+xf8Qr1fANqZveFhjIdTsTRLt7BkfxpmrWwHKn6g1szQq6KMCUECtHToe9qrCwA/UC0p4+rNofd3PnlF51dTPvP8ZG1Yy7U0=
    - GIT_DEPLOY_REPO=https://$GH_TOKEN@github.com/putaindecode/putaindecode.io.git

deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
