language: node_js
before_install:
  - gem --version
  - gem update --system
# global requirements
  - make init
  - make install
# local requirements
  - make update
# grunt-webfont requirements
  - sudo apt-get install fontforge
# for some test with dates
  - sudo cp /usr/share/zoneinfo/Europe/Paris /etc/localtime

notifications:
  irc: "irc.freenode.org#p!"
